### Create a new order
POST http://localhost:8080/api/checkout/create-checkout-session
Content-Type: application/json
Authorization: Bearer token

{
  "shippingAddress": "123 Main St, Springfield, IL",
  "billingAddress": "456 Elm St, Springfield, IL",
  "paymentMethod": "CREDIT_CARD",
  "orderItems": [
    {
      "productId": 1,
      "quantity": 1
    }
  ]
}

### Get all orders
GET http://localhost:8080/api/orders
Content-Type: application/json
Authorization: Bearer token

### Get order by ID
GET http://localhost:8080/api/orders/1
Content-Type: application/json
Authorization: Bearer token

### Update order status
PATCH http://localhost:8080/api/orders/1?status=PROCESSING
Content-Type: application/json
Authorization: Bearer token