### Add product

POST http://localhost:8080/api/products/admin
Content-Type: application/json
Authorization: Bearer your-access-token

{
  "title": "Milk",
  "description": "This is a new product.",
  "price": 99.9,
  "imageUrl": "https://placehold.co/600x400/EEE/31343C",
  "categoryId": 1
}